version: '3'
services:
  api:
    build:
      context: document_q_and_a/api
    ports:
      - '8000:8000'
    env_file:
      - .env

  client:
    build:
      context: document_q_and_a/client
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    volumes:
      - frontend:/app

volumes:
  backend: {}
  frontend: {}
